blueprint:
  name: Z2M - Sonoff wireless Button SNZB-01P
  description:
    Configure actions for the Sonoff Zigbee Wireless Button SNZB-01P using Zigbee2MQTT.
    Define actions for single, double, and long press events.
  domain: automation
  input:
    button_id:
      name: Button
      description: The button to configure.
      selector:
        device:
          filter:
            - integration: mqtt
              model: Wireless button
              manufacturer: SONOFF
          multiple: false
    single_press_action:
      name: Single Press Action
      description: Action to perform on Single Press.
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to perform on Double Press.
      default: []
      selector:
        action: {}
    long_press_action:
      name: Long Press Action
      description: Action to perform on Long Press.
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent

triggers:
  - trigger: device
    domain: mqtt
    type: action
    device_id: !input button_id
    subtype: single
  - trigger: device
    domain: mqtt
    type: action
    device_id: !input button_id
    subtype: double
  - trigger: device
    domain: mqtt
    type: action
    device_id: !input button_id
    subtype: long

action:
  - choose:
      - conditions:
          - "{{ trigger.payload == 'single' }}"
        sequence: !input single_press_action
      - conditions:
          - "{{ trigger.payload == 'double' }}"
        sequence: !input double_press_action
      - conditions:
          - "{{ trigger.payload == 'long' }}"
        sequence: !input long_press_action
